### ISSUE TITLE
SN Utils doesn't adapt to minimized sidebar in Studio

### ISSUE THREAD

**Issue by chasingtheflow** [arnoudkooi/ServiceNow-Utils#536]
![CleanShot 2024-09-16 at 13 22 30@2x](https://github.com/user-attachments/assets/51b31d7b-7d85-4435-b00a-1646f325bc8a)

Notice the Link to VS Code button / text doesn't adapt / hide when the sidebar is minimized.

**Comment by chasingtheflow** [comment]
Adding something like the below css would resolve for me:

```css
nav.hide-explorer > app-explorer > a,
nav.hide-explorer > app-explorer > input {
        display: none;
}
```
